# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
# MehungryServer.Repo.insert!(%MehungryServer.SomeSchema{})
require Logger

{:ok, language_gr} = MehungryServer.Repo.insert(%MehungryServer.Language{name: "Gr"})
{:ok, language_en} = MehungryServer.Repo.insert(%MehungryServer.Language{name: "En"})

{:ok, gram} = MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnit{name: "gram"})
{:ok, kg} = MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnit{name: "kg"})
{:ok, ml} = MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnit{name: "ml"})
{:ok, mg} = MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnit{name: "mg"})

MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnitTranslation{name: "γραμμάριο", language_id: language_gr.id, measurement_unit_id: gram.id})
MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnitTranslation{name: "κιλό", language_id: language_gr.id, measurement_unit_id: kg.id})
MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnitTranslation{name: "ml", language_id: language_gr.id, measurement_unit_id: ml.id})
MehungryServer.Repo.insert(%MehungryServer.Food.MeasurementUnitTranslation{name: "mg", language_id: language_gr.id, measurement_unit_id: mg.id})

{:ok, dairy} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Dairy"})
{:ok, vegetables} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Vegetables"})
{:ok, fruits} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Fruits"})
{:ok, baking_and_grains} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Baking & Grains"})
{:ok, added_sweeteners} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Added sweeteners"})
{:ok, spices} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Spices"})
{:ok, meats} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Meats"})
{:ok, fish} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Fish"})
{:ok, seafood} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Seafood"})
{:ok, oils} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Oils"})
{:ok, seasonigs} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Seasonigs"})
{:ok, sauces} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Sauces"})
{:ok, legumes} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Legumes"})
{:ok, alcohol} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Alcohol"})
{:ok, soup} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Soup"})
{:ok, nuts} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Nuts"})
{:ok, dairy_alternatives} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Dairy Alternatives"})
{:ok, deasert_and_snacks} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Deserts & Snacks"})
{:ok, beverages} = MehungryServer.Repo.insert(%MehungryServer.Food.Category{name: "Beverages"})

MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Καρυκεύματα", category_id: seasonigs.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Σάλτσες", category_id: sauces.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Όσπρια", category_id: legumes.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Αλκοολούχα", category_id: alcohol.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Σούπες", category_id: soup.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Ξηροι καρποί", category_id: nuts.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Yποκατάστατα γαλακτοκομικών", category_id: dairy_alternatives.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Snack", category_id: deasert_and_snacks.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Ποτά", category_id: beverages.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Γαλακτοκομεικά", category_id: dairy.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Λαχανικά", category_id: vegetables.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Φρούτα", category_id: fruits.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "ψησίματος και καρποί", category_id: baking_and_grains.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "πρόσθετα γλυκαντικά", category_id: added_sweeteners.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "μπαχαρικά", category_id: spices.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Κρέας", category_id: meats.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Ψάρι", category_id: fish.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Θαλασιννά", category_id: seafood.id, language_id: language_gr.id})
MehungryServer.Repo.insert(%MehungryServer.Food.CategoryTranslation{name: "Λάδι", category_id: oils.id, language_id: language_gr.id})

{_, chicken_breast} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "chicken breast", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "κοτόπουλο στοίθος", language_id: language_gr.id, ingredient_id: chicken_breast.id })

{:ok, ground_beef} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "ground beef", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "κιμας μοσχαρίσιος", language_id: language_gr.id,  ingredient_id: ground_beef.id})

#{:ok, bacon} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "bacon", category: meats, measurement_unit: gram})
#MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "μπέικον", language_id: language_gr.id, ingredient_id: bacon.id})

{:ok, sausage} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "sausage", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "λουκάνικο", language_id: language_gr.id, ingredient_id: sausage.id})

{:ok, beef_steak} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "beef steak", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "μοσχαρίσια μπριζόλα", language_id: language_gr.id, ingredient_id: beef_steak.id })

{:ok, ham} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "ham", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "ζαμπόν", language_id: language_gr.id, ingredient_id: ham.id})

{:ok, hot_dog} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "hot dog", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "λουκάνικο", language_id: language_gr.id, ingredient_id: hot_dog.id})

{:ok, pork_chops} = MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pork chops", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.IngredientTranslation{name: "χοιρινη μπριζόλα", language_id: language_gr.id, ingredient_id: hot_dog.id})

MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "chicken thighs", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "ground turkey", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "cooked chicken", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "turkey", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pork", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pepperoni", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "whole chicken", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "chicken leg", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "ground pork", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "chorizo", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "chicken wings", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "beef roast", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pork roast", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "ground chicken", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pork ribs", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "venison", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pork shoulder", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "bologna", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "bratwurst", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "prosciutto", category: meats, measurement_unit: gram})

MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "lamb", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "chicken roast", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "lamb chops", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pancetta", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "ground lamb", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "beef ribs", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "duck", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pork belly", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "beef liver", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "leg of lamb", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "canadian bacon", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "beef shank", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "veal", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "chicken giblets", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "cornish hen", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "lamb shoulder", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "lamb shank", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "deer", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "ground veal", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pastrami", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "rabbit", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "slicked turkey", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "pork loin", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "elk", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "beef suet", category: meats, measurement_unit: gram})
MehungryServer.Repo.insert(%MehungryServer.Food.Ingredient{name: "corned beef", category: meats, measurement_unit: gram})


